name: Publish to Docker Hub

on:
  push:
    branches: 
      - v*
      - master

env:
  IMAGE_NAME: firefox-send

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u alanway --password-stdin

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Push image
        run: |
          IMAGE_ID=alanway/$IMAGE_NAME
          
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "image id: $IMAGE_ID"

          VERSION=$(echo "${{ steps.vars.outputs.short_ref }}" | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo "version: $VERSION"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION